### ISSUE TITLE
Belati TODO List

### ISSUE THREAD

**Issue by aancw** [aancw/Belati#12]
## TODO
- [ ] Automatic OSINT with Username and Email support
- [ ] Organization or Company OSINT Support
- [ ] Collecting Data from Public service with Username and Email for LinkedIn and other service.
- [ ] Token Support
- [ ] Email Harvesting with multiple content(github, linkedin, etc)
- [ ] Scrapping Public Document with multiple search engine(yahoo, yandex, bing etc)
- [ ] Scanning Report export to PDF
- [ ] Domain or subdomain reputation checker
- [ ] Reporting Support to JSON, PDF
- [ ] Graph Visualization
- [x] Web Server Only Mode
- [ ] Shodan API Implementation
- [x] Metadata Extractor
- [x] Auto Update Feature
- [x] Change webserver binding to 0.0.0.0:8000
- [ ] Document Viewer for Public Document Gathering
- [x] Clear Output String
- [ ] Use BuiltWith instead of Wappalyzer
- [x] Command Line Shell module like msfconsole
- [ ] Log name centralization
- [x] Replace sublist3r with DNSDumpster only
- [ ] Create setup.py installation
- [x] Release stable version

If you have suggest feature or reference resource, please let me know :)

**Comment by attacker34** [comment]
Please make a separate or you can adjust in this tool about the subdomains list which redirects to main domain and which are not.. which show 404,403 and their applications like apache etc :)

**Comment by aancw** [comment]
Hi! 
Thanks for your suggestion. I've plan to replace sublist3r with dnsdumpster package because new sublist3r have different result :)

**Comment by lplume** [comment]
Hello! you should take a look at [maldevel/EmailHarvester](https://github.com/maldevel/EmailHarvester); i think some of your todos might benefits from that tool.

regards

**Comment by aancw** [comment]
Hi @lplume, I've created my own mail harvest based on his repository and theharvester. Am i missing something? Let me know which one should i implement.

Thanks!

**Comment by aancw** [comment]
Belati command line shell preview:

https://asciinema.org/a/r88yqh3zmTRjBLrYHiXrWAqxu

**Comment by necrose99** [comment]
**SETUP.PY** 

then it works on almost everything.
